/*
 * Copyright 2014 Azige.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.azige.lrcplayer;

import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;

import javax.swing.JFileChooser;
import javax.swing.Timer;

import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.util.Duration;

/**
 *
 * @author Azige
 */
public class LyricPlayer extends javax.swing.JFrame{

    private MediaPlayer player;
    private Timer timer;
    private Lyric lrc;
    private LyricTimeLine timeLine;
    private LyricEvent currentEvent;
    private boolean sliderTrace = true;
    private final JFileChooser fileChooser;

    /**
     * Creates new form LyricPlayer
     */
    public LyricPlayer(){
        initComponents();
        // To init JavaFX
        new JFXPanel();
        fileChooser = new JFileChooser();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stopButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lyricTextArea = new javax.swing.JTextArea();
        timeLabel = new javax.swing.JLabel();
        timeLineSlider = new javax.swing.JSlider();
        totalTimeLabel = new javax.swing.JLabel();
        playToggleButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lyric Player");
        setResizable(false);

        stopButton.setText("Stop");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        lyricTextArea.setEditable(false);
        lyricTextArea.setColumns(20);
        lyricTextArea.setLineWrap(true);
        lyricTextArea.setRows(5);
        jScrollPane1.setViewportView(lyricTextArea);

        timeLabel.setText("00:00.00");

        timeLineSlider.setEnabled(false);
        timeLineSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timeLineSliderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                timeLineSliderMouseReleased(evt);
            }
        });

        totalTimeLabel.setText("00:00.00");

        playToggleButton.setText("Play");
        playToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playToggleButton)
                .addGap(48, 48, 48)
                .addComponent(stopButton)
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLineSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalTimeLabel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel)
                    .addComponent(timeLineSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stopButton)
                    .addComponent(playToggleButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        stop();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void timeLineSliderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeLineSliderMousePressed
        sliderTrace = false;
    }//GEN-LAST:event_timeLineSliderMousePressed

    private void timeLineSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeLineSliderMouseReleased
        seek();
        refreshView(timeLineSlider.getValue());
        sliderTrace = true;
    }//GEN-LAST:event_timeLineSliderMouseReleased

    private void playToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playToggleButtonActionPerformed
        if (playToggleButton.isSelected()){
            if (player == null){
                openMediaFile();
                play();
            }else{
                resume();
            }
        }else{
            pause();
        }
    }//GEN-LAST:event_playToggleButtonActionPerformed

    private void openMediaFile(){
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File mediaFile = fileChooser.getSelectedFile();
            player = new MediaPlayer(new Media(mediaFile.toURI().toString()));
            player.setOnEndOfMedia(this::stop);
            File lrcFile = new File(mediaFile.getParentFile(), mediaFile.getName().replaceAll("\\.[^\\.]*$", "") + ".lrc");
            if (lrcFile.exists()){
                try{
                    lrc = new LyricReader(new InputStreamReader(new FileInputStream(lrcFile), "UTF-8")).readLyric();
                }catch (Exception ex){
                    lrc = null;
                    throw new RuntimeException(ex);
                }
            }else{
                lrc = null;
            }
            if (lrc != null){
                timeLine = new LyricTimeLine(lrc);
            }else{
                lyricTextArea.setText("歌词不可用");
            }
        }
    }

    private void play(){
        player.play();
        int totalTime = (int)player.getMedia().getDuration().toMillis();
        totalTimeLabel.setText(LyricTimeStamp.fromMillis(totalTime).toString());
        timeLineSlider.setMaximum(totalTime);
        timeLineSlider.setEnabled(true);
        timer = new Timer(10, this::timerLisener);
        timer.start();
        stopButton.setEnabled(true);
    }

    private void timerLisener(ActionEvent e){
        refreshView((int)player.getCurrentTime().toMillis());
    }

    private void refreshView(int time){
        timeLine.setTime(time);
        if (sliderTrace == true){
            timeLineSlider.setValue(time);
        }
        timeLabel.setText(LyricTimeStamp.fromMillis(time).toString());
        if (currentEvent != timeLine.getCurrentEvent()){
            currentEvent = timeLine.getCurrentEvent();
            lyricTextArea.setText(currentEvent.getLyric());
        }
    }

    private void pause(){
        player.pause();
        timer.stop();
    }

    private void resume(){
        player.play();
        timer.start();
    }

    private void stop(){
        timer.stop();
        player.dispose();
        player = null;
        lyricTextArea.setText("");
        timeLabel.setText("00:00.00");
        totalTimeLabel.setText("00:00.00");
        timeLineSlider.setMaximum(2);
        timeLineSlider.setValue(1);
        timeLineSlider.setEnabled(false);
        stopButton.setEnabled(false);
        playToggleButton.setSelected(false);
    }

    private void seek(){
        player.seek(Duration.millis(timeLineSlider.getValue()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try{
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
                if ("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(LyricPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch (InstantiationException ex){
            java.util.logging.Logger.getLogger(LyricPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch (IllegalAccessException ex){
            java.util.logging.Logger.getLogger(LyricPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch (javax.swing.UnsupportedLookAndFeelException ex){
            java.util.logging.Logger.getLogger(LyricPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                new LyricPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lyricTextArea;
    private javax.swing.JToggleButton playToggleButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JSlider timeLineSlider;
    private javax.swing.JLabel totalTimeLabel;
    // End of variables declaration//GEN-END:variables
}
